---
- hosts: test-servers
  sudo: yes
  tasks:
     - name: be sure httpd is installed
       yum: name=httpd state=installed

     - name: be sure httpd is running and enabled
       service: name=httpd state=running enabled=yes
