---
- name: download oracle jdk1.8
  command: 'wget -q -O {{JAVA_DL_PATH}} --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" {{JAVA_DL_URL}} creates={{JAVA_DL_PATH}}'
  poll: 10

- name: be sure java8 installed
  yum: name={{JAVA_DL_PATH}} state=installed
