---
# tasks for sonar install
- name: get the sonar repository
  get_url: url={{SONAR_REPO_URL}} dest={{SONAR_REPO_DL_PATH}}

- name: be sure sonar is insatlled
  yum: name=sonar state=latest

- name: be sure sonar is running and enabled
  service: name=sonar state=running enabled=yes
